BEGIN {
    FS = "\t"

    print "/* This file is automatically generated. DO NOT EDIT. */"
    print ""
    print "#include <vector>"
    print "#include \"kjv_data.h\""
    print ""
    print "std::vector<kjv_verse> kjv_verses = {"

    book_count = 0
}

# awk 'BEGIN{ print "hello" }  { $1=$2="";gsub("^ +","");print $0 }  END{ print "goodbye" } '
{
    book_name         = $1 
    book_abbreviation = $2 
    book_number       = $3 
    chapter_number    = $4 
    verse_number      = $5 
    verse             = $6

    printf( "    {%d, %d, %d, \"%s\"},\n",
        book_number, chapter_number,
        verse_number, verse )

    
    if (!(book_number in book_names)) {
        book_names[book_number] = book_name
        book_abbrs[book_number] = book_abbreviation
        book_count++
    }
}

END {
    print "};"

    print "std::vector<kjv_book> kjv_books = {"
    for (i = 1; i <= book_count; i++) {
        printf("    {%d, \"%s\", \"%s\"},\n", i, book_names[i], book_abbrs[i])
    }
    print "};"
}
