BEGIN {
    print "/* This file is automatically generated. DO NOT EDIT. */"
    print ""
    print "#include \"quran_data.h\""
    print ""

    i             = 0
    surah_count   = 0
    current_surah = 0
}

{
    sub(/#.*$/ , "", $0)
    sub(/\s*$/ , "", $0)
    sub(/^\s*$/, "", $0)

    if (length($0) > 0) {
        split($0,parts,"\t")
        Surah = parts[1]
        Ayat  = parts[2]
        Text  = parts[3]
        gsub(/"/,"\\\"",Text)

        if(Surah != current_surah) {
            if(current_surah != 0) {
                lines[i++] = "    },"
            }
            lines[i++] = sprintf("    [%d] {", Surah)
            current_surah = Surah
            ++surah_count
        }
        lines[i++] = sprintf("        [%d] \"%s\",", Ayat, Text)
    }
}

END {
    lines[i++] = "    }"
    printf("char* quran[][%d] = {\n", surah_count)
    for(j = 0; j < i; ++j) {
        print lines[j]
    }
    print "};"
    print ""
    printf("int surah_count = %d;\n", surah_count)
}

