BEGIN {
    print "/* This file is automatically generated. DO NOT EDIT. */"
    print ""
    print "#include \"quran_data.h\""
    print ""
    print "quran_verse quran_verses[] = {"

    book_count = 0
}

{
    FS = "\t"
    Sura = $1 
    Ayat = $2 
    Text = $3 
    printf("    {%d, %d, \"%s\"},\n", Sura, Ayat, Text)
}

#TODO: this is half done, it's still working from being copied from the bible's generate.awk

END {
    print "};"
    print ""
    printf("int quran_verses_length = %d;\n", NR)
    print ""

    print "quran_book quran_books[] = {"
    for (i = 1; i <= book_count; i++) {
        printf("    {%d, \"%s\", \"%s\"},\n", i, book_names[i], book_abbrs[i])
    }
    print "};"

    print ""
    printf("int quran_books_length = %d;\n", book_count)
}
