#!/usr/bin/awk -f
BEGIN {
    surah_count = 0; n = -1
}

{
    sub(/#.*$/ , "", $0)
    sub(/\s*$/ , "", $0)
    sub(/^\s*$/, "", $0)
    if (length($0) > 0) {
        split($0,parts,"\t")
        Surah = parts[1]
        Ayat  = parts[2]
        Text  = parts[3]
        gsub(/"/,"\\\"",Text) # escape quotations in text for C string literal
        if(Surah != current_surah) {
            if(length(current_surah) != 0) {
                lines[++n] = "    },"
            }
            current_surah = Surah
            lines[++n]    = sprintf("    [%d] {", Surah)
            ++surah_count
        }
        lines[++n] = sprintf("        [%d] \"%s\",", Ayat, Text)
    }
}

END {
    lines[++n] = "    }"
    n_lines = n
    n = -1
    print "/* This file is automatically generated. DO NOT EDIT. */"
    print ""
    print "#include \"quran_data.h\""
    print ""
    printf("const int   N_SURAHS    = %d;\n", surah_count)
    printf("const char* quran[][%d] = {\n", surah_count)
    while (n < n_lines) {
        print lines[++n]
    }
    print "};"
}
