BEGIN {
    print "/* This file is automatically generated. DO NOT EDIT. */"
    print ""
    print "#include \"quran_data.h\""
    print ""
    print "char* quran[][surah_count] = {"

    surahs        = 0
    current_surah = 0
}

{
    sub(/#.*$/ , "", $0)
    sub(/\s*$/ , "", $0)
    sub(/^\s*$/, "", $0)

    if (length($0) > 0) {
        split($0,parts,"\t")
        Surah = parts[1]
        Ayat  = parts[2]
        Text  = parts[3]
        gsub(/"/,"\\\"",Text)

        if(Surah != current_surah) {
            if(current_surah != 0) {
                printf("    },\n")
            }
            printf("    [%d] {\n", Surah)
            current_surah = Surah
            ++surah_count
        }

        printf("        [%d] \"%s\",\n", Ayat, Text)
    }
}

END {
    print "    }"
    print "};"
    print ""
    printf("int surah_count = %d;\n", surah_count)
}

